### PR TITLE
Implemented Azure AD B2C

### PR DESCRIPTION
**Pull request by jmoran-cei**
Implemented: 
- Authentication & Authorization w/ appropriate tokens and scopes for accessing API endpoints
- Microsoft Graph API calls via HttpClient to AD B2C for accessing user data
- updated/versioned UserService and UserController to operate with AD B2C tenant rather than storing user data

In-Progress: 
- changing models for Trip <-- TripMember --> User many-to-many relationship to query Microsoft Graph for up-to-date user data for when accessing trip endpoints

---------
This process has been taking me a lot longer than I'd hoped for. I'm enjoying it and learning a lot but it's been a struggle trying to version my entity models so that the endpoints/methods can continue to operate even if older versions are accessed. Trying to work on doing that currently. If it gives me too much trouble I'll probably just replace old methods/models instead of having old and new work. The old user model will not be accessed by the frontend anymore.

What is pushed as of now can be reviewed; however, I have more changes to come.

### CODE REVIEW

**Comment by swhook52** [comment]
Just sharing a few approaches to versioning. Here's one I like (ignoring the red). Version at a very top level with the expectation that when things change, that change will involve all operations with that model. You can do that versioning scheme across all projects. Another method is to always work off of the latest and create conversion methods from v1, v2, etc.

I can show you some examples when you would like.
image

**Comment by jmoran-cei** [comment]
I've completed versioning my API and implementing AD B2C with my backend. Instead of headers, I changed versioning to be based on URL path because it makes more sense since my entire controllers were versioned. It also allows me to exclude the need for providing a version when accessing the most recent version — e.g. `api/trips` defaults to the same controller as `api/v3/trips`. That saves me from having to make sure api paths don't need to be changed on the frontend anytime a new version is added to the backend.

Only thing I didn't complete was adding new tests and re-structuring my existing tests to work with the versioned services. I'll do that sometime in the future after I finish getting my entire project to work correctly end-to-end. This PR is ready for re-review.

**Comment by jmoran-cei** [comment]
### For better visual

 - snippet of my project structure:
image

 - Swagger Documentation:
   - v1
image


   - v2
image


   - v3
image

**Comment by irwinhurstCEI** [comment]
I'm late to the party here but I am going disagree with Steve's versioning method.  I'm not saying it is wrong, there isn't a right answer.  I just want to give you some other things to think about.

Looking at your project, this style of versioning has led to a few concerns:
1. Open Close Principle: Interfaces/Objects are open to extension and Closed to changes.  So if all you are doing is adding new methods then there is no reason to make a new version.  New versions are only needed when you make a breaking change to the interface or object.  
2. It creates too much duplicated code.  A quick look at your TripDTo shows that it hasn't changed but you have 3 copies of it.
3. If this was a shared API, you will now need to support 3 completely separate versions. You can slowly deprecate old ones but most of the time you end up supporting duplicate versions because other people are still using it V1.
4. Constantly copying every controller and every object just because you changed 1 method will cause cascading code changes and a massive amount of updates for no added value.  Even your angular project will need to updates all of it's routes just because of 1 method change.
5. If you are going to follow this method, move your Interfaces and Services to a different layer.  This will allow you to share the same service code/DTOs across multiple versions of your controller. You have 3 copies of your TripService that could more easily been shared as one interface and one service. 
These methods are identical except the name
- TripService.GetTripB2CAsync(long id)
- TripService.GetAsync(long id)

My preferred method is make a copy of the controller, and only when I make a breaking change. So you can be on TripsV3 and UsersV1.
TripsController
  [HttpGet("api/trips")]
  Task<ActionResult<TripDto>> GetAsync([FromRoute] long id)
TripsControllerV2
  [HttpGet("api/v2/trips")]  (I prefer [HttpGet("api/trips/v2")], but its your call)
  Task<ActionResult<TripDto>> GetAsync([FromRoute] long id)

TripsControllerV3
   [HttpGet("api/v3/trips")]
   Task<ActionResult<TripDto>> GetTripAsync([FromRoute] long id)

You can also use the HttpsGet attribute to control routing instead of your projects structure.  And when methods dont change you even send multiple versions to the same method like this:
   [HttpGet("api/v2/trips")]
   [HttpGet("api/v3/trips")]
   Task<ActionResult<TripDto>> GetAsync([FromRoute] long id)

Good luck. As I said, just another perspective.

**Comment by jmoran-cei** [comment]
@irwinhurstCEI I value and appreciate your added insight. After receiving your input I've restructured it again.

I removed the former v1 as I originally unnecessarily created v2 as duplicate async methods of v1 and should have just updated the methods as asynchronous instead of versioning v1. I now have just a v1 (original async methods) and v2 (implements AD B2C entity and DTO changes for `/trips` and Microsoft Graph API Get requests for `/users`. There are no duplicate methods as the entities utilized have changes and DTOs are different; this is also why I decided to keep the two controllers separate because all versioned and added methods are breaking changes. I changed the paths to better correlate with a lower level of versioning — before: `api/v1/trips` now: `api/trips/v2`. I also compiled my versioned services to now be one shared interface/service for all versions. 

Snippet of my project directory:
image


Here is the swagger UI of my two versions:
v1
image


v2
image

**Comment by irwinhurstCEI** [comment]
@jmoran-cei  I think this looks better and if this was a larger project it would be easier to maintain over time.  thanks.

**Pull request merged**
